apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.20.0
          ports:
            - containerPort: 4442 # Event bus
            - containerPort: 4443 # Event bus
            - containerPort: 4444 # UI and WebDriver
          env:
            - name: SE_GRID_BROWSER_TIMEOUT
              value: "300"
            - name: SE_GRID_TIMEOUT
              value: "300"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"